CREATE SCHEMA `garage`;
CREATE TABLE `garage`.`cars` (
  `idcars` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `brand` VARCHAR(100) NULL,
  `model` VARCHAR(45) NULL,
  `year` INT NULL,
  `price` FLOAT NULL DEFAULT 0,
  `description` VARCHAR(1000) NULL,
  `secondhand` VARCHAR(45) NULL DEFAULT 'no',
  `km` FLOAT NULL DEFAULT 0,
  `co2` FLOAT NULL DEFAULT 0,
  `fuel` VARCHAR(45) NULL,
  `transmission` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `nb_places` VARCHAR(45) NULL,
  `DIN_power` INT NULL DEFAULT 0,
  PRIMARY KEY (`idcars`));
CREATE TABLE `garage`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL DEFAULT 'employee',
  `name` VARCHAR(45) NULL,
  `fam_name` VARCHAR(45) NULL,
  `birth` VARCHAR(45) NULL,
  `adress` VARCHAR(250) NULL,
  `zipcode` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `social_security` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'employed',
  `created` DATE NULL,
  `updated` VARCHAR(100) NULL,
  `pay` FLOAT NULL DEFAULT 1747.20,
  `grade` VARCHAR(45) NULL DEFAULT 'regular',
  PRIMARY KEY (`idemployee`));
